### ISSUE TITLE
Error occurred while retrieving token.

### ISSUE THREAD

**Issue by A333333** [lsiddiquee/com.rexwel.bmwconnected#1]
Hi, appreciate your work, this is what I was waiting for!

issue: installed the app en successfully signed in with my Connecteddrive account but while adding BMW in Devices, it prompted with: Error occurred while retrieving token.

I installed the app several times and tried again. Still the same.

Info: I have a BMW 1 series, latest model, petrol. Account BMW connected is valid, car is connected in the official BMW App

**Comment by lsiddiquee** [comment]
Which country you are using it from? Also after the weekend I will create a test version with logging hopefully that will help to isolate the issue.

**Comment by A333333** [comment]
Hi, I am living in the Netherlands.
Take your time, appreciate it.

**Comment by A333333** [comment]
Hi, when I got my car this morning I noticed that my BMW was not valid anymore. I linked it to my login for your Homey app. Seems that the format of my excisting password doesn't meet new  requirements. I've changed my BMW ID password en I could login with your BMW app. Seems to be working now! Happy testing! 
Thanks and regards, Adri

**Comment by lsiddiquee** [comment]
Glad it worked.  Otherwise on site debugging was also an option as I am based in NL as well.

**Comment by A333333** [comment]
Thanks again!
