### ISSUE TITLE
Refuel flow will not activate

### ISSUE THREAD

**Issue by romigithub** [lsiddiquee/com.rexwel.bmwconnected#11]
After sucessfully defining and connecting my car, i defined a flow. In the 'when' card, only the refuel appears with the according 4 tags. When i want to test the flow, the 'start test' appears, the tags have according values, however the then card are not executed. Also the flow shows inactive in the flow overview, even though in the settings it is set to actif.

**Comment by lsiddiquee** [comment]
If this is still the case please reopen the issue.
