### ISSUE TITLE
Feature proposal

### ISSUE THREAD

**Issue by MaSkars** [lsiddiquee/com.rexwel.bmwconnected#13]
Hi, 
Thanks for a nice app. 
I have a proposal that would be great if you would consider implementing and that is the ability to track the battery temperature on a BEV like the i3 in order or see how the battery preconditioning is behaving using insight in Homey. If it's possible that is. 
Thanks

**Comment by lsiddiquee** [comment]
Hi, Indeed if the api was providing this information. Can easily incorporate it. Btw do you see this info on the connected drive app? I have tested with a PHEV and normal petrol cars. I dont have access to a BEV hence dont know if the api returns that info.

**Comment by MaSkars** [comment]
No that info is not in the app unfortunately so I guess it might not be available "outside" the vehicle.

**Comment by lsiddiquee** [comment]
As this information is not available in the BMW Connected app, it cannot be retrieved using the API. Hence closing this issue as this cannot be implemented.
