### ISSUE TITLE
Wont fetch my car: "Error occurred while attempting 'GET' at url 'https://b2vapi.bmwgroup.com/webapi/v1/user/ with 403 body (Null)"

### ISSUE THREAD

**Issue by jdhont77** [lsiddiquee/com.rexwel.bmwconnected#15]

**Comment by jdhont77** [comment]
![278376759_1506828819778318_3964746351176474356_n](https://user-images.githubusercontent.com/104248094/164883203-1ff77b03-0eef-45d2-a802-417f25f72b21.png)
I just installed the app for the first time

**Comment by lsiddiquee** [comment]
@jdhont77 can you try the latest version of the app.

**Comment by jdhont77** [comment]
Hi, I was able to add my car now!
Thanks!
I not yet tested any functionality.

Van: Likhan Siddiquee ***@***.***>
Verzonden: vrijdag 17 juni 2022 20:59
Aan: lsiddiquee/com.rexwel.bmwconnected ***@***.***>
CC: jdhont77 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [lsiddiquee/com.rexwel.bmwconnected] Wont fetch my car: "Error occurred while attempting 'GET' at url 'https://b2vapi.bmwgroup.com/webapi/v1/user/ with 403 body (Null)" (Issue #15)


@jdhont77<https://github.com/jdhont77> can you try the latest version of the app.

**Comment by lsiddiquee** [comment]
Due to no response closing the issue.
