### ISSUE TITLE
Stopped working on the 12-13 of April

### ISSUE THREAD

**Issue by JohanKSE** [lsiddiquee/com.rexwel.bmwconnected#16]
Hi, not sure what has happened but it seems that the app can't connect to the car anymore. It still reports all data but they are the same ever since the 12th of April. 

I hope you have a chance to look att it soon, should you need help testing pls let me know.

**Comment by eaasnes** [comment]
Same issue here. Checked with another that uses this app, and he has the same problem. No updates. 

Really hope you get a chance to fix this soon!

**Comment by lsiddiquee** [comment]
@JohanKSE @eaasnes  Due to the change in BMW services, everything was broken, and I also due to some personal issues could not fix them. However, with the latest version it should be working again. Can you validate and let me know.

**Comment by JohanKSE** [comment]
Hi Likhan, hope that everything is fine with you?

Thanks for this, I figured it would be something like that so no worries,
just appreciate that you got around to adapt it.

I will check it over the weekend, have already noticed that one of my flows
are back up although the total mileage is a bit weird. The total mileage on
the car is 42 184 but the readout I get from your app is 26 210.

Also noticed that it also started logging every 1-5 km of driving, however
this could be due to my previous workaround so I need to look into that
before I say anything for sure.

But as said, I will look into to it properly over the next few days.


Den fre 17 juni 2022 kl 14:14 skrev Likhan Siddiquee <
***@***.***>:

**Comment by eaasnes** [comment]
Everything seems to be working here now. Also tested the Climate Now function, and that’s working as well. 

@JohanKSE I’m having the same issue with mileage readout. Seems like it shows miles instead of kilometres. @lsiddiquee Is it possible to change this back to kilometres, or maybe an option to select between miles and kilometres?

**Comment by lsiddiquee** [comment]
The api now only returns miles. I will add an option in the app to set miles or km and then will convert whatever the api returns. I just wanted to unblock everybody.

Regards
Likhan
________________________________

**Comment by JohanKSE** [comment]
HI Likhan & co,

@eaasnes Yepp, was a bit slow and didn't figure out that it was in miles :), as long as I know what measurement is returned I can always convert it so that's good.

One thing that does not seem to work though is the DriveSession Completed that I used to use in conjunction with Generic alarm to determine if the drive has ended or not. Not it gets triggered several times during a drive.

But in all fairness the most important part form me is to be able to logg mileage daily, the other stuff is just added pleasure :).

**Comment by JohanKSE** [comment]
@Likhan: OK, thanks. It would be ideal to be able to use it as a drive log
but for me at least it's a luxury function, I'm just so happy being able to
log daily milage again, save me ton of work.

Den mån 20 juni 2022 kl 11:03 skrev Likhan Siddiquee <
***@***.***>:

**Comment by lsiddiquee** [comment]
Closing stale issue
