### ISSUE TITLE
403: error when attempting to retrieve token

### ISSUE THREAD

**Issue by Royarne83** [lsiddiquee/com.rexwel.bmwconnected#17]
Hu,
I get this message when trying to connect to the bmw app. Any idea why?

Diagnosis code: abcf0ac1-5c65-4d34-b463-503af616a95e

**Comment by lsiddiquee** [comment]
@Royarne83 Due to the change in BMW services, everything was broken, and I also due to some personal issues could not fix them. However, with the latest version it should be working again. Can you validate and let me know.

**Comment by Royarne83** [comment]
Works! Thanks a lot 👍🏻
