### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by MaSkars** [lsiddiquee/com.rexwel.bmwconnected#19]
Hi, 

I have used your app previously and were specifically happy about the battery level and the charging status. 
However a few months ago that stopped working completely so I stopped using the app. 
Now when it was updated I was hoping it would go back to the same (or better) status that it had before but unfortunately it has not. At least not in my case. 
I have two i3s -21 and prevously the data from the car was read but no controls were working. 
No after the update the controls are still not working. Unfortunately neither does the reading of data with one exception. The odometer is reported however not in kilometers but in miles. 
Nothing else works.

**Comment by fossaaen** [comment]
Same status for my i3  - 19.

**Comment by lsiddiquee** [comment]
Please reopen if this is still the case.
