### ISSUE TITLE
Error message when trying to connect

### ISSUE THREAD

**Issue by sonnyshogun** [lsiddiquee/com.rexwel.bmwconnected#23]
Hi

Get this error message when I try to connect:
Error occurred while attempting 'GET' at url 'https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=120&appDateTime=1663493252334&tireGuardMode=ENABLED' with 403 body (null)

What am I doing wrong?

Thanks in advance!

**Comment by FreekieVT** [comment]
Hi, I have the same issue. And I do have the latest version of the app (I guess, since I added it via Homey) v0.1.3 ?

**Comment by FreekieVT** [comment]
BTW I've reinstalled the app, restarted the homey, re-entered my credentials etc. but unfortunately no succes :-(

**Comment by eddiex666** [comment]
same error here...
tryed to reset password 10 times, the mobile app is working.
HASS and OpenHAB is not working..
Maybe BMW did some changes to stop/clock smarthouse API.
or changes in authentication API.

**Comment by eddiex666** [comment]
Any news?

**Comment by ivan-skjavik** [comment]
I still get this error. What can the issue be?

**Comment by lsiddiquee** [comment]
Indeed this did come back due to some changes to the BMW API. And I was not able to fix it as we just had our son and super busy. However, a new version has been pushed and should fix the issue now. Please test and respond if there are any issues.

**Comment by FreekieVT** [comment]
Great, I'll give it a try soon

**Comment by lsiddiquee** [comment]
Due to inactivity closing this issue. Hopefully the issue is resolved, otherwise please reopen or create a new issue. Thanks
