### ISSUE TITLE
Mileage , fuel and range values dont get updated anymore

### ISSUE THREAD

**Issue by dacootmeister** [lsiddiquee/com.rexwel.bmwconnected#26]
version 0.1.5 of the app, I find that values for Mileage , fuel and range values dont get updated anymore in the Homey dashboard
![image](https://user-images.githubusercontent.com/35705080/205687858-4c7569af-f1bc-4e73-a54e-362fbb565e94.png)

**Comment by lsiddiquee** [comment]
Hello @dacootmeister. These values are only updated when there is a change. If they are not getting updated, can you try going into the app settings, and updating the password to see if it can successfully connect. You might need to change the password to invalid, try saving then fix it and try saving again.

**Comment by lysdioden** [comment]
Hi @lsiddiquee I have the same problem, mine updates the location of the car only at night at the same time every night. the last time it worked was 1/12.

**Comment by lsiddiquee** [comment]
Apologies for the delayed response. @dacootmeister and @lysdioden can you check in your car, if all data sharing is enabled. Is the data in the app updated in realtime?

**Comment by lsiddiquee** [comment]
No response in a long time, hence closing the ticket.
