### ISSUE TITLE
`Device#setCapabilityOptions` being called a lot

### ISSUE THREAD

**Issue by robertklep** [lsiddiquee/com.rexwel.bmwconnected#27]
I noticed in a diagnostics report for my own app HomeKitty that your app is changing devices quite often, which I traced down to calls being made to `setCapabilityOptions` (for example [here](https://github.com/lsiddiquee/com.rexwel.bmwconnected/blob/6474dd41ad959e8ca5a8cdddd08c18d2fcd71702/drivers/bmw/device.ts#L188)).

According to [the documentation](https://apps-sdk-v3.developer.homey.app/Device.html#setCapabilityOptions), this is an expensive operation so should only be called when needed 😊 It looks like you can make those calls to the device's `onInit` instead of with every status update.

**Comment by lsiddiquee** [comment]
Thanks @robertklep for pointing this out. I will work on to improve this.

**Comment by lsiddiquee** [comment]
Fixed with PR #32
