### ISSUE TITLE
BMW Homey App v0.1.5 not updating data since 19 days

### ISSUE THREAD

**Issue by dacootmeister** [lsiddiquee/com.rexwel.bmwconnected#30]
I noticed my BMW Homey App not updating data since 19 days. Restarting doesnt help.
The logfile doesnt show any typical denial of service... polling seems to work with BMW Connected drive

Debug log: 81534d18-a5b0-4e73-8720-f1219c44d4cc

Can you pls have a look ? Thnks

**Comment by lsiddiquee** [comment]
@dacootmeister thanks for reporting this. For some reason i was not getting any notification on from github. I was as well a but busy with our new born. I will hopefully push a fix this week or next week latest.

**Comment by lsiddiquee** [comment]
Please use the test version and see if this fixes the issue.
https://homey.app/nl-nl/app/com.rexwel.bmwconnected/BMW-Connected/test/

**Comment by lsiddiquee** [comment]
Due to inactivity closing this issue. Hopefully the issue is resolved, otherwise please reopen or create a new issue. Thanks
