### ISSUE TITLE
Error message when trying to install new device

### ISSUE THREAD

**Issue by Effendi68** [lsiddiquee/com.rexwel.bmwconnected#31]
I installed the app first time. App-Installation was succesfull but when I try to install a device I get this error message: 

Error occurred while attempting 'GET at url
"https://cocoapi.bmwgroup.com/eadrax-vcs/v2/vehicles?
zone=120&appDateTime=1690022595583&tireGuardMode=ENABLED'
04 body (null) {"statusCode": 404, message": "Resource not found}

Has anyone an idea?

**Comment by ivan-skjavik** [comment]
Same error here.

**Comment by Marsattacks12** [comment]
Same error. It stopped working and when I tried to make a new connection I got this message

**Comment by ericfran** [comment]
same here :-(

**Comment by lsiddiquee** [comment]
Thanks for reporting this. For some reason i was not getting any notification on from github. I was as well a but busy with our new born. I will hopefully push a fix this week or next week latest.

**Comment by lsiddiquee** [comment]
Please use the test version and see if this fixes the issue.
https://homey.app/nl-nl/app/com.rexwel.bmwconnected/BMW-Connected/test/

**Comment by ericfran** [comment]
Hi,This experimental version seems already to work a lot better.Véhicule discoveredA lot of measure collectedThanks RegardsEric On 17 Aug 2023, at 17:14, Likhan Siddiquee ***@***.***> wrote:﻿
Please use the test version and see if this fixes the issue.
https://homey.app/nl-nl/app/com.rexwel.bmwconnected/BMW-Connected/test/

**Comment by ivan-skjavik** [comment]
Nice! It works now 👍

**Comment by lsiddiquee** [comment]
Great to know it is now working again.
