### ISSUE TITLE
Mileage and Range Incorrect

### ISSUE THREAD

**Issue by Chris-Starkey** [lsiddiquee/com.rexwel.bmwconnected#34]
Hi, I'm driving a (petrol) 218i in the UK and the app works mostly fine. No connection problems at all, lock/unlock etc work perfectly.

But the mileage is way too high, showing 140,000 when my actual mileage is about 48,000. That's UK miles. The range is also incorrect, currently showing 526 (assume miles?) when the actual is about 300 miles.

Maybe the range is showing in kilometers, conversion would be about right. But I don't understand where the car's mileage is coming from.

Any ideas would be great. Thanks.

**Comment by lsiddiquee** [comment]
Hi, Currently indeed the value is returned as is what is received from the BMW service. I will try to see if I can find some time to add a configuration to switch the units in the app.

**Comment by lsiddiquee** [comment]
@Chris-Starkey There is a test version 0.2.2 pushed where you can switch between miles and km. Can you test and provide feedback. Thanks

https://tools.developer.homey.app/apps/app/com.rexwel.bmwconnected/build/32

**Comment by lsiddiquee** [comment]
Added support for switching between miles/km and l/gal (us)/gal (uk).
