### ISSUE TITLE
Unable to lock my car

### ISSUE THREAD

**Issue by jeffmcfly** [lsiddiquee/com.rexwel.bmwconnected#36]
Hi. Sometimes, when send a lock request to my car, nothing happen. In rare cases, the car locks the doors, but never the alarm is armed. 

I've a BMW X1 sDrive18d. How can I help to find the root cause?

**Comment by lsiddiquee** [comment]
Hi @jeffmcfly, can you share what is the build year of the car? Also the alarm cannot be armed using the app. You can also see this exact behavior when using the lock/unlock command from the app. I guess BMW decided that the only way to arm the alarm is either using the keyfob or using comfort opening, which still uses the keyfob. I think there is a secured handshake happening to turn the immobilizer.

**Comment by jeffmcfly** [comment]
Hi. The VIN is WBA71AC0305V2861, the production year is 2022. Thx for the information for the alarm.

**Comment by lsiddiquee** [comment]
Are the other information updated regularly?

**Comment by jeffmcfly** [comment]
Yes, it seems so.

**Comment by lsiddiquee** [comment]
@jeffmcfly can you confirm if you are still facing the issue regarding the lock/unlock working intermittently, and also if this is something you are facing with the app as well.

**Comment by lsiddiquee** [comment]
Closing the issue due to no response in a long while. If you encounter this issue again, please reopen and provide the clarifications as requested thanks.
