### ISSUE TITLE
Location and geofencing conditions not available in app

### ISSUE THREAD

**Issue by Tukker2021** [lsiddiquee/com.rexwel.bmwconnected#38]
Hello, 

When I create a flow and try to use the location or geofencing as a condition this is not possible, as those options are not available:
![IMG_2314](https://github.com/lsiddiquee/com.rexwel.bmwconnected/assets/88245214/2c6f4436-db07-4541-80e1-0261b7308789)

**Comment by Tukker2021** [comment]
Even after installing the a test version 0.2.2 where you can switch between miles and km, there is no change in the behavior

https://tools.developer.homey.app/apps/app/com.rexwel.bmwconnected/build/32

**Comment by Tukker2021** [comment]
I have followed your instructions, but I still do not get the option to select "Location Changed" or "Geo-fence - Enter" or "Geo-fence - Exit" as the download page suggests:https://homey.app/en-nl/app/com.rexwel.bmwconnected/BMW-Connected/test/
![image](https://github.com/lsiddiquee/com.rexwel.bmwconnected/assets/88245214/f13918b4-3873-4962-a5c4-d275b3eb5791)

I did drove my vehicle to outside my geo-fence, then locked it and left it there for 30 minutes. I have the following flows to check for any changes, and although I did got some notification "BMW Alarm went true" there is no change in the Location or Geo-Fence features being enabled. 
![image](https://github.com/lsiddiquee/com.rexwel.bmwconnected/assets/88245214/35df5049-2f76-4914-b5d3-b2304c3dcacb)

Neither do the other options (e.g. vehicle locked) have a label that can be used to test the location. So there is no way I can check for the vehicle to be at home or at any other location!

**Comment by Tukker2021** [comment]
So basically the IF Location Changed card is missing, would installing the official version of the app make a difference?
https://homey.app/en-us/app/com.rexwel.bmwconnected/BMW-Connected/

**Comment by lsiddiquee** [comment]
@Tukker2021 I have removed the filter for now, can you try the latest version and see if that gives you the cards?

**Comment by Tukker2021** [comment]
Hello,Yes, the cards are now visible, I will test them.Met vriendelijke groetenRick Stroot————————————Op 8 jan 2024 om 11:04 heeft Likhan Siddiquee ***@***.***> het volgende geschreven:﻿
@Tukker2021 I have removed the filter for now, can you try the latest version and see if that gives you the cards?
