### ISSUE TITLE
After installing the 0.2.1 version I have performance issues

### ISSUE THREAD

**Issue by Tukker2021** [lsiddiquee/com.rexwel.bmwconnected#39]
After installing the 0.2.1 version, it seems that the BMW app is heavily impacting my Homey Pro, as I often get the message now that it is no reachable!

**Comment by Tukker2021** [comment]
![image](https://github.com/lsiddiquee/com.rexwel.bmwconnected/assets/88245214/631b2d94-42b4-46bb-b893-9b70c20bda92)

**Comment by lsiddiquee** [comment]
Looking at this graph, you can clearly see that the app is not using the CPU and the memory consumption is stable as well. It does not look like the app is causing any performance issue.

**Comment by lsiddiquee** [comment]
Any update on this issue?
