### ISSUE TITLE
[Feature request] add 'and..' card for battery percentage 

### ISSUE THREAD

**Issue by JordVisbeen** [lsiddiquee/com.rexwel.bmwconnected#43]
Hi, been using your app on Homey and it works like a charm. 

It would be nice to have the option to check the battery percentage in an 'and' card, so some actions only can proceed if there is enough power. 
Example: Climate the car, but only if the battery percentage is 'higher than xx%'

I now use a workaround by copying the batt% into a local variable, and use that in an And card. 

A 'lower than xx%' card would be equally appreciated. 

Thanks for your support! 
Edit: car=iX1 (bev)

**Comment by lsiddiquee** [comment]
Feature added and currently available in test build available https://homey.app/en-nl/app/com.rexwel.bmwconnected/BMW-Connected/test/.

Please verify and let me know if there are any issues.

**Comment by JordVisbeen** [comment]
![image](https://github.com/lsiddiquee/com.rexwel.bmwconnected/assets/62200522/924c2702-a9b9-40ca-a259-f1989d50ab32)
Tested it working. Thank you, also for the other additions! 
This week already stepped several times into a pre-heated de-iced car without having to think about it, thanks to Homey 🥳
