### ISSUE TITLE
Device lost connection to car, can't reinstall

### ISSUE THREAD

**Issue by punkportaldan** [lsiddiquee/com.rexwel.bmwconnected#49]
Hi, first of all, thanks for this great plugin! I have used it for some time with my Homey Pro but after a few weeks it stopped updating info from my car. I have tried to delete it and reinstall it but ended up with this error message. Tried to restart Homey but the issue persist. Please let me know if I can help with troubleshooting it. Thanks!
![image](https://github.com/lsiddiquee/com.rexwel.bmwconnected/assets/33433686/2719100a-8baf-4042-a05c-f8bbdfed86c6)

**Comment by punkportaldan** [comment]
Now I see a similar thread already exists. Please delete this if not needed. Thanks

**Comment by punkportaldan** [comment]
I removed the plugin and reinstalled, added data and managed to readd the app.

**Comment by lsiddiquee** [comment]
closing this, duplicate #45
