### ISSUE TITLE
BMW blocks account login due to ‘bot activity’

### ISSUE THREAD

**Issue by Bulldozerdkdk** [lsiddiquee/com.rexwel.bmwconnected#54]
Whenever I use my account for the Homey they block my ability to log into the account on my phone and the functionality stops working and no data is being updated in the homey app.

BMW connected drive support just informs me that they block will be revoked once I stop using Homey.

Anyone manage to work around this with success?

App is kinda worthless if it is being blocked by BMW

**Comment by SteenLauritzen** [comment]
Same for me. The scipt is pinging BMW server 600 times/hour. We need a possibility in the configuration to set the pinging speed

**Comment by lsiddiquee** [comment]
In the devices setting you can set the polling interval. Personally i have set it to 300 and never had any issues with it.
