### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by JordVisbeen** [lsiddiquee/com.rexwel.bmwconnected#58]
Hi, since nov 17 connection with the BMW app seems lost.
After this date the actual battery status is not updated anymore and car doesn't respond on commands like opening/locking.
See picture attached (you would expect normal usage like shown before nov 17).
I've tried to reset Homey, reset app, include geolocation (mentioned here), nothing works. 
I'm afraid to delete the app, maybe cannot find my car anymore at all...
What can be the cause?
Thanks in advance!

![Lost connection](https://github.com/user-attachments/assets/8abb0315-9d4d-47dc-9ee0-9fa321082b4d)

**Comment by Modestsailor** [comment]
I have same problem, lost contact with my BMW 8 days ago. Tried deleting app and reinstalling, now the app doesn’t let me log inn. I get (error:aborted)

**Comment by jeroen1973** [comment]
Had the same problem. Got in contact with bmw customerservices and they changed the polling interval of their api. And when it’s contacted to much it will block your ipadres.  They say they can’t manually unblock it. Also they have an captcha now wich you need to enter before logging in.

**Comment by Effendi68** [comment]
Login in my Mini-Account is not possible. BMW / Mini now need an Captcha at first login. Please update the homey App with the possibility for a captcha. I use EVCC App for my PV and this App integrated the captcha yesterday. Thank you.

**Comment by SteenLauritzen** [comment]
BMW closed for my BMW ConnectedDrive due to too many requests. The Script is polling 600 time/hour and this will make BMW to black list my account. Please change the app not to pole the BMW server more than5-10 times/hour

**Comment by Voorslub** [comment]
> BMW closed for my BMW ConnectedDrive due to too many requests. The Script is polling 600 time/hour and this will make BMW to black list my account. Please change the app not to pole the BMW server more than5-10 times/hour

You can set the polling interval in Homey’s advanced settings of the car. Have set it to 1800 sec now. Hopefully the car comes back alive now.

**Comment by SteenLauritzen** [comment]
Even after I'm now able to access my BMW account, Homey is still unable. Any solution for this problem?
![chrome_GMX3FiXlbH](https://github.com/user-attachments/assets/1d5f5eb2-a926-433f-818b-b4866ad90849)

**Comment by LukDG** [comment]
Hi, same here. I got locked out a few weeks ago in the Homey App, and now I got also locked out now due to the amount of authentication failures against the API.

**Comment by lsiddiquee** [comment]
Check #62
