### ISSUE TITLE
Mini connected, can't connect Wrong details

### ISSUE THREAD

**Issue by kayintveen** [lsiddiquee/com.rexwel.bmwconnected#59]
Dear @lsiddiquee 

I would love to add our mini electric to Homey. 
But unfortunately I'm not able to. it says wrong credentials. While I just confirmed by logging in to the connected app on iPhone as well as on the connected website that my credentials are good.

Is there a bug?
made a bug report: 58fb09cd-3387-489a-b6c4-e5fdec80a121

**Comment by lsiddiquee** [comment]
Duplicate #62
