### ISSUE TITLE
Error when using Climate Now or Lock/Unlock

### ISSUE THREAD

**Issue by eaasnes** [lsiddiquee/com.rexwel.bmwconnected#6]
Everything seems to be set up correctly because battery, range, fuel status etc. updates with correct values. When trying to activate Climate Now it gives an error (see image below). Not sure if msgId contains sensitive information so I censored that too. Tell me if you need it.

A similar message appears when trying to lock or unlock the car. The car supports these features because I can use them from the official BMW app on my phone. 

Also getting an error when trying to send a message to the car using a flow. No error message, just a red triangle with exclamation mark. Not sure if it’s related to the other errors. 

![0604205B-D8D6-4979-9400-0D363477CF0C](https://user-images.githubusercontent.com/70980197/132923757-4a8785d1-2967-41be-b8c3-823cf53543a8.jpeg)
![7EFF48CF-36C0-4B29-9CFC-C4A56EA71B7E](https://user-images.githubusercontent.com/70980197/132924097-517dd6a1-0d26-4c9c-bdd1-197809ba1422.png)

**Comment by MaSkars** [comment]
I have the same issues on my i3s 2021.

**Comment by romigithub** [comment]
The same on my setup

**Comment by lsiddiquee** [comment]
The services are currently not working. Will fix it hopefully soon.

**Comment by Crunch1969** [comment]
Same issue here. Hope it can be fixed soon. It is a wonderful app, really appreciate your efforts.

**Comment by lsiddiquee** [comment]
@eaasnes @jakubsarvas @MaSkars @romigithub @Crunch1969 Remote services now should be working again. Please check and validate.
