### ISSUE TITLE
BMW Homey App Login Failed 

### ISSUE THREAD

**Issue by Driver81** [lsiddiquee/com.rexwel.bmwconnected#60]
Hallo zusammen, 
ich hoffe ihr könnte mir weiterhelfen. Ich habe das Problem, dass ich mich nicht mehr in die BMW Homey App einloggen kann. Ich bekomme immer die Fehlermeldung, Login Failed. Meine Zugangsdaten sind aber korrekt und ich kann mich damit auch in die Fahrzeug App einloggen. Löschen der Homey BMW App hat leider auch nichts gebracht. Wo kann hier der Fehler liegen?

Ich danke euch im Voraus für eine Rückmeldungen!

Beste Grüße,
Andreas

**Comment by lsiddiquee** [comment]
Duplicate #62
