### ISSUE TITLE
BMW fail to login

### ISSUE THREAD

**Issue by giocoo** [lsiddiquee/com.rexwel.bmwconnected#61]
I installeren bmw app at Homey. When i want to login, i get the message “ data niet correct”.

login the bmw connected app in my phone is wording fine
 Want can i do

quote="Gio_Coo, post:1, topic:123960"]
Ik heb de Homey pro. Ik heb de BMW app geïnstalleerd. Ik wil vervolgens een apparaat aanmaken en moet inloggen. Naar ik aanneem in de BmW app. Ik ga er dan ook van uit dat dit de zelfde gegevens zijn als de app die op mijn telefoon staat.

Als ik mijn gegevens invoer krijg ik de melding “ gegevens niet correct”

Ik weet zeker dat username en we correct worden ingevoerd.

Heeft iemand hier de zelfde ervaring mee en hoe is dit op te lossen?
[/quote]

**Comment by lsiddiquee** [comment]
Duplicate #62
