### ISSUE TITLE
Not able to connect my bmw

### ISSUE THREAD

**Issue by Oper1989** [lsiddiquee/com.rexwel.bmwconnected#64]
I have lost connection with my bmw. I have both tried to reinstall the app and restarted my homey. 
The password has also been reset. 
The fault message is: "The user details provided are invalid". But I have double checked all details.

**Comment by lsiddiquee** [comment]
Fixed in the latest test version available at https://homey.app/nl-nl/app/com.rexwel.bmwconnected/BMW--Mini-Connected/test/
